### ISSUE TITLE
Fork from original

### ISSUE THREAD

**Issue by ierpe** [123host/speakout-email-petitions#1]
Hi, I am currently starting to work with the speak up plugin.
It's great that you took over from the other repo if it's not active anymore, but you should have forked from the original repo first, and then committed your changes...
Right now I cannot know what changed you have made, since you didn't fork the original repo (Why.. ?) and you have no changes log...

You say you did some updates, but what are they?

**Comment by 123host** [comment]
Hey piero,

I didn't fork it because while I am quite experienced with php I am not
with subversion.  It has always confused me :P. I didn't realise that was
the correct process.

Couldn't you just do a diff on files to find the changes?

Steve
123host

Some tips and ideas - http://setup.123host.com.au

**Comment by ierpe** [comment]
Hi,
As the name of the website suggests, here Git is used, not subversion :-p
If you want to use github I strongly recommend to start learning a little about git, otherwise no one will follow / use your repo...

I could do a diff of course, but that completely defeats the purpose of working collaboratively with Git...
